import CTModels: CTModels

# # Abstract types
# import CTModels:
#     AbstractOptimalControlProblem,
#     AbstractOptimalControlInitialGuess,
#     AbstractOptimalControlSolution,
#     AbstractOptimizationProblem,
#     AbstractOptimizationModeler,
#     AbstractOptimizationSolver

# PreModel
import CTModels: PreModel

# Modelers
import CTModels:
    ADNLPModeler,
    ExaModeler

# OptimalControlProblem setters, builders
import CTModels:
    variable!,
    time!,
    state!,
    control!,
    dynamics!,
    constraint!,
    objective!,
    definition!,
    time_dependence!,
    build

# Initial guess
import CTModels: initial_guess

#,
#     # setters
#     variable!,
#     time!,
#     state!,
#     control!,
#     dynamics!,
#     #    constraint!,
#     objective!,
#     definition!,
#     time_dependence!,
#     # model
#     build,
#     Model,
#     PreModel,
#     Solution,
#     # getters
#     constraints,
#     get_build_examodel,
#     times,
#     definition,
#     dual,
#     initial_time,
#     initial_time_name,
#     final_time,
#     final_time_name,
#     time_name,
#     variable_dimension,
#     variable_components,
#     variable_name,
#     state_dimension,
#     state_components,
#     state_name,
#     control_dimension,
#     control_components,
#     control_name,
#     #    constraint,
#     dynamics,
#     mayer,
#     lagrange,
#     criterion,
#     has_fixed_final_time,
#     has_fixed_initial_time,
#     has_free_final_time,
#     has_free_initial_time,
#     has_lagrange_cost,
#     has_mayer_cost,
#     is_autonomous,
#     export_ocp_solution,
#     import_ocp_solution,
#     time_grid,
#     control,
#     state,
#     #    variable,
#     costate,
#     constraints_violation,
#     #    objective,
#     iterations,
#     status,
#     message,
#     infos,
#     successful,
#     AbstractOptimalControlProblem,
#     AbstractOptimizationProblem,
#     AbstractOptimalControlInitialGuess,
#     AbstractOptimalControlSolution,
#     AbstractOptimizationModeler
# # export AbstractOptimalControlProblem,
# #     AbstractOptimizationProblem,
# #     AbstractOptimalControlInitialGuess,
# #     AbstractOptimalControlSolution,
# #     AbstractOptimizationModeler
# export Model, Solution
# export constraints,
#     get_build_examodel,
#     times,
#     definition,
#     dual,
#     initial_time,
#     initial_time_name,
#     final_time,
#     final_time_name,
#     time_name,
#     variable_dimension,
#     variable_components,
#     variable_name,
#     state_dimension,
#     state_components,
#     state_name,
#     control_dimension,
#     control_components,
#     control_name,
#     #    constraint,
#     dynamics,
#     mayer,
#     lagrange,
#     criterion,
#     has_fixed_final_time,
#     has_fixed_initial_time,
#     has_free_final_time,
#     has_free_initial_time,
#     has_lagrange_cost,
#     has_mayer_cost,
#     is_autonomous,
#     export_ocp_solution,
#     import_ocp_solution,
#     time_grid,
#     control,
#     state,
#     #    variable,
#     costate,
#     constraints_violation,
#     #    objective,
#     iterations,
#     status,
#     message,
#     infos,
#     successful