blank_issues_enabled: false
contact_links:
  - name: OptimalControl.jl support
    url: https://github.com/control-toolbox/OptimalControl.jl/discussions
    about: Please ask and answer questions about OptimalControl.jl here.
  - name: control-toolbox support
    url: https://github.com/orgs/control-toolbox/discussions
    about: Please ask and answer questions about control-toolbox ecosystem here.
