blank_issues_enabled: false
contact_links:
  - name: Control-toolbox support
    url: https://github.com/orgs/control-toolbox/discussions
    about: Please ask and answer questions about control-toolbox ecosystem here.
