# Ref: https://securitylab.github.com/research/github-actions-preventing-pwn-requests
name: Breakage Application

# read-only repo token
# no access to secrets
on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  break:
    if: contains(github.event.pull_request.labels.*.name, 'run breakage applications')
    strategy:
      fail-fast: false
      matrix:
        pkgname: [CalculusOfVariations, LossControl, GeometricPreconditioner, MedicalResonanceImaging, Kepler]
        pkgversion: [latest, stable]
        include:
          - pkgpath: control-toolbox
    uses: control-toolbox/CTActions/.github/workflows/breakage-application..yml@main
    with:
      pkgname: ${{ matrix.pkgname }}
      pkgpath: ${{ matrix.pkgpath }}
      pkgversion: ${{ matrix.pkgversion }}
