name: CI

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
    
jobs:
  test-cpu-github:
    uses: control-toolbox/CTActions/.github/workflows/ci.yml@main
    with:
      runs_on: '["ubuntu-latest", "macos-latest"]'
      runner_type: 'github'
      use_ct_registry: true
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}

  # Job pour le runner self-hosted kkt (GPU/CUDA)
  test-gpu-kkt:
    uses: control-toolbox/CTActions/.github/workflows/ci.yml@main
    with:
      versions: '["1"]'
      runs_on: '[["kkt"]]'
      runner_type: 'self-hosted'
      use_ct_registry: true
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}