name: CI

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
    types: [labeled, opened, synchronize, reopened]
    
jobs:
  test-cpu-github:
    if: contains(github.event.pull_request.labels.*.name, 'run ci cpu')
    uses: control-toolbox/CTActions/.github/workflows/ci.yml@main
    with:
      versions: '["1.12"]'
      runs_on: '["ubuntu-latest", "macos-latest"]'
      runner_type: 'github'
      use_ct_registry: false
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}

  # Job pour le runner self-hosted kkt (GPU/CUDA)
  test-gpu-kkt:
    if: contains(github.event.pull_request.labels.*.name, 'run ci gpu')
    uses: control-toolbox/CTActions/.github/workflows/ci.yml@main
    with:
      versions: '["1"]'
      runs_on: '[["kkt"]]'
      runner_type: 'self-hosted'
      use_ct_registry: false
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
