name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
    types: [labeled, opened, synchronize, reopened]
  
jobs:
  call:
    if: contains(github.event.pull_request.labels.*.name, 'run documentation')
    uses: control-toolbox/CTActions/.github/workflows/documentation.yml@main
    with:
      use_ct_registry: true
    secrets:
      SSH_KEY: ${{ secrets.SSH_KEY }}
