name = "CTSolvers"
uuid = "d3e8d392-8e4b-4d9b-8e92-d7d4e3650ef6"
version = "0.3.6-beta"
authors = ["Olivier Cots <olivier.cots@toulouse-inp.fr>"]

[deps]
ADNLPModels = "54578032-b7ea-4c30-94aa-7cbd1cce6c9a"
CTBase = "54762871-cc72-4466-b8e8-f6c8b58076cd"
CTModels = "34c4fa32-2049-4079-8329-de33c2a22e2d"
CommonSolve = "38540f10-b2f7-11e9-35d8-d573e4eb0ff2"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ExaModels = "1037b233-b668-4ce9-9b63-f9f681f55dd2"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
NLPModels = "a4795742-8479-5a88-8948-cc11e1c8c1a6"
SolverCore = "ff4d7338-4cf1-434d-91df-b86cb86fb843"

[weakdeps]
MadNCL = "434a0bcb-5a7c-42b2-a9d3-9e3f760e7af0"
MadNLP = "2621e9c9-9eb4-46b1-8089-e8c72242dfb6"
MadNLPMumps = "3b83494e-c0a4-4895-918b-9157a7a085a1"
NLPModelsIpopt = "f4238b75-b362-5c4c-b852-0801c9a21d71"
NLPModelsKnitro = "bec4dd0d-7755-52d5-9a02-22f0ffc7efcb"

[extensions]
CTSolversIpopt = "NLPModelsIpopt"
CTSolversKnitro = "NLPModelsKnitro"
CTSolversMadNCL = ["MadNCL", "MadNLP", "MadNLPMumps"]
CTSolversMadNLP = ["MadNLP", "MadNLPMumps"]

[compat]
ADNLPModels = "0.8"
Aqua = "0.8"
BenchmarkTools = "1"
CTBase = "0.18"
CTModels = "0.9"
CUDA = "5"
CommonSolve = "0.2"
DocStringExtensions = "0.9"
ExaModels = "0.9"
KernelAbstractions = "0.9"
MadNCL = "0.1"
MadNLP = "0.8"
MadNLPGPU = "0.7"
MadNLPMumps = "0.5"
NLPModels = "0.21"
NLPModelsIpopt = "0.11"
NLPModelsKnitro = "0.10"
OrderedCollections = "1.8"
Random = "1"
SolverCore = "0.3"
Test = "1"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
MadNLPGPU = "d72a61cc-809d-412f-99be-fd81f4b8a598"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "BenchmarkTools", "CUDA", "MadNCL", "MadNLP", "MadNLPGPU", "MadNLPMumps", "NLPModelsIpopt", "OrderedCollections", "Random", "Test"]
